name: Create Release

on:
  push:
    tags:
      - 'v*'  # v1.0.0, v2.1.3 などのタグがプッシュされた時にトリガー

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create zip archive
      run: |
        zip -r AirInertiaReturns.zip bin/
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: AirInertiaReturns.zip
        body: |
          ## Changes in this release
          
          ### Installation
          1. Download the `AirInertiaReturns.zip` file
          2. Extract the contents to your Cyberpunk 2077 game directory
          
          ### What's included
          - Cyber Engine Tweaks mod files
          - All necessary plugin files
        draft: false
        prerelease: false